services:
  db:
    image: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vehicle
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 42333:3306